version: '3.8'

services:
  sqlite-viewer:
    image: coleifer/sqlite-web
    container_name: omniscore_sqlite_viewer
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./database:/data
    environment:
      - SQLITE_DATABASE=app.db
  db:
    image: postgres:16-alpine
    container_name: betwin_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: betwin_db
    ports:
      - "5433:5432"
    volumes:
      - betwin_postgres_data:/var/lib/postgresql/data

volumes:
  betwin_postgres_data:
    external: true
